services:
  - type: web
    name: sitebound-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --reload"
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false